receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:12346

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      "api-key": b3968879d17906bb2b985d70232c6449FFFFNRAL

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [spanmetrics, batch]
    metrics:
      receivers: [otlp/spanmetrics, otlp]
      exporters: [prometheus]
      processors: [batch]
      exporters: [otlp]
